version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb3123-container
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend-assign2:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend-assign2:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend-assign2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
